In [25]:
import pandas as pd
from experiments_metadata import *
from results_utils import get_results_summary
pd.options.plotting.backend = "plotly"

df_raw = get_results_summary()

In [31]:
all_results = []
for model in MODEL_NAMES_LIST:
    for horizon in HORIZONS:
        df_horizon_identity = df_raw[(df_raw["model"] == model) & (df_raw["metric"] == "mse") & (df_raw["shaping_process"] == "identity") & (df_raw["horizon"] == horizon)].copy()
        df_horizon = df_raw[(df_raw["model"] == model) & (df_raw["metric"] == "mse") & (df_raw["horizon"] == horizon)].copy()

        identity_value = df_horizon_identity["value"].values[0]
        df_horizon["identity_value"] = identity_value
        df_horizon["improvement"] = (1 - df_horizon["value"] / identity_value) * 100

        all_results += [df_horizon]

df = pd.concat(all_results).sort_values(by="improvement").dropna()
df

,dataset,horizon,shaping_process,shaping_window,model,metric,value,identity_value,improvement
0,ETTh1,720,ipentropy,1501,NBEATSx,mse,0.18874461,0.12786053,-47.61757876
0,ETTh1,96,ipmutual_info,501,NBEATSx,mse,0.10897412,0.07466489,-45.95094890
0,ETTh1,720,iprollcorr,1001,BiTCN,mse,0.19544835,0.13520688,-44.55503917
0,ETTh1,720,pfarm,1001,BiTCN,mse,0.19007916,0.13520688,-40.58394603
0,ETTh1,192,pmutual_info,1251,TSMixerx,mse,0.12816049,0.09120635,-40.51707754
...,...,...,...,...,...,...,...,...,...
0,ETTh1,720,pentropy,1001,GRU,mse,0.22990244,0.32708243,29.71116408
0,ETTh1,720,pfarm,501,LSTM,mse,0.21057086,0.30194265,30.26130482
0,ETTh1,720,prollcov,501,LSTM,mse,0.20363364,0.30194265,32.55883592
0,ETTh1,720,pfarm,751,LSTM,mse,0.19998476,0.30194265,33.76730207
0,ETTh1,720,pmutual_info,501,LSTM,mse,0.19953578,0.30194265,33.91599901

In [37]:
improv_summary_list = []

for shaping_process in SHAPING_PROCESSES:

    df_improvement_count = df[df["shaping_process"] == shaping_process].copy()

    pos_improv = len(df_improvement_count[df_improvement_count["improvement"] > 0])
    neu_improv = len(df_improvement_count[df_improvement_count["improvement"] == 0])
    neg_improv = len(df_improvement_count[df_improvement_count["improvement"] < 0])
    improv_summary_list += [{
        "pos_improv" : pos_improv,
        "neu_improv" : neu_improv,
        "neg_improv" : neg_improv,
        "shaping_process" : shaping_process
    }]

pd.DataFrame().from_records(improv_summary_list)

   pos_improv  neu_improv  neg_improv shaping_process
0           0          43           0        identity
1          63          20         132           pfarm
2          59          20         136       prollcorr
3          68          20         126        prollcov
4          69          20         126        pentropy
5          86          20         109    pmutual_info
6          73          20         121      iprollcorr
7          72          20         123       iprollcov
8          73          20         122       ipentropy
9          55          20         140   ipmutual_info

# Predictions
---

In [64]:
import pandas as pd

model = "NHITS"
horizon = 96
shaping_process = "identity"
shaping_window = 501
dataset = "ETTh1"


if shaping_process == "identity":
    shaping_window = "N/A"

if shaping_window == "N/A":
    filename = f"./results/{dataset}_na_{shaping_process}/{model}_horizon{horizon}/pred.parquet"
else:
    filename = f"./results/{dataset}_w{shaping_window}_{shaping_process}/{model}_horizon{horizon}/pred.parquet"

df = pd.read_parquet(filename)

df

,unique_id,ds,cutoff,NHITS,y
0,OT_raw,2017-10-23 23:00:00,2017-10-23 22:00:00,-0.95490104,-0.92608918
1,OT_raw,2017-10-24 00:00:00,2017-10-23 22:00:00,-0.96067226,-0.90083221
2,OT_raw,2017-10-24 01:00:00,2017-10-23 22:00:00,-0.98170161,-0.90921125
3,OT_raw,2017-10-24 02:00:00,2017-10-23 22:00:00,-0.96860695,-0.86707657
4,OT_raw,2017-10-24 03:00:00,2017-10-23 22:00:00,-0.95721728,-0.91759040
...,...,...,...,...,...
267451,OT_raw,2018-02-20 19:00:00,2018-02-16 23:00:00,-1.38267124,-2.00387717
267452,OT_raw,2018-02-20 20:00:00,2018-02-16 23:00:00,-1.38914549,-2.00387717
267453,OT_raw,2018-02-20 21:00:00,2018-02-16 23:00:00,-1.38995016,-1.77656492
267454,OT_raw,2018-02-20 22:00:00,2018-02-16 23:00:00,-1.40135813,-1.74280923
267455,OT_raw,2018-02-20 23:00:00,2018-02-16 23:00:00,-1.41149199,-1.72605108

In [66]:
cutoff_list = df["cutoff"].tolist()
df[df["cutoff"] == cutoff_list[1000]].drop(["unique_id", "cutoff"], axis=1).set_index("ds").plot()